import {
  FaCode,
  FaTools,
  FaGitAlt,
  FaSearch,
  FaHandsHelping,
  FaCheckSquare,
  FaRocket,
  FaLightbulb,
  FaBriefcase,
  FaBook,
  FaChartLine,
  FaCog,
  FaUserFriends,
  FaClipboardList,
  FaComments,
  FaUser,
  FaLock,
  FaUnlock,
  FaEnvelope,
  FaPhone,
  FaCalendar,
  FaMapMarkerAlt,
  FaLink,
  FaShareAlt,
  FaSave,
  FaEdit,
  FaTrash,
  FaPlus,
  FaMinus,
  FaUpload,
  FaDownload,
  FaFile,
  FaFileAlt,
  FaFilePdf,
  FaFileWord,
  FaFileExcel,
  FaFileImage,
  FaFileAudio,
  FaFileVideo,
  FaFileArchive,
  FaHeart,
  FaStar,
  FaShoppingCart,
  FaDollarSign,
  FaCreditCard,
  FaMedkit,
  FaHospital,
  FaShower,
  FaBath,
  FaBed,
  FaCoffee,
  FaBeer,
  FaPizzaSlice,
  FaApple,
  FaAndroid,
  FaWindows,
  FaLinux,
  FaAppleAlt,
  FaBasketballBall,
  FaFootballBall,
  FaBaseballBall,
  FaTableTennis,
  FaGolfBall,
  FaTachometerAlt,
  FaRunning,
  FaDumbbell,
  FaArchway,
  FaBuilding,
  FaCity,
  FaHome,
  FaStore,
  FaWarehouse,
  FaTruck,
  FaShip,
  FaPlane,
  FaTrain,
  FaTaxi,
  FaSubway,
  FaBicycle,
  FaWalking,
  FaMountain,
  FaSun,
  FaMoon,
  FaCloud,
  FaCloudSun,
  FaCloudMoon,
  FaUmbrella,
  FaSnowflake,
  FaWind,
  FaLayerGroup,
  FaShieldAlt,
  FaAngular,
  FaDatabase,
  FaDocker,
  FaFlask,
  FaJava,
  FaJenkins,
  FaLaravel,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaRProject,
  FaRust,
  FaSwift,
  FaVuejs,
  FaBookReader,
  FaSync,
  FaPlayCircle,
  FaUniversity,
  FaProjectDiagram,
  FaHistory,
} from "react-icons/fa";
import {
  FaBookOpen,
  FaCalculator,
  FaCalendarCheck,
  FaCalendarDay,
  FaCodeBranch,
  FaCss3,
  FaGithub,
  FaGitlab,
  FaGraduationCap,
  FaJs,
  FaNetworkWired,
  FaRobot,
  FaSitemap,
  FaTerminal,
  FaThumbsUp,
  FaUsers,
} from "react-icons/fa6";
import { GoArrowUpRight, GoZap } from "react-icons/go";
import { TbSquareRoundedChevronsUpFilled } from "react-icons/tb";

export const icons = [
  { name: "Code", code: "FaCode", icon: FaCode },
  { name: "Tools", code: "FaTools", icon: FaTools },
  { name: "Git", code: "FaGitAlt", icon: FaGitAlt },
  { name: "Search", code: "FaSearch", icon: FaSearch },
  { name: "Helping Hands", code: "FaHandsHelping", icon: FaHandsHelping },
  { name: "Check", code: "FaCheckSquare", icon: FaCheckSquare },
  { name: "Rocket", code: "FaRocket", icon: FaRocket },
  { name: "Idea", code: "FaLightbulb", icon: FaLightbulb },
  { name: "Work", code: "FaBriefcase", icon: FaBriefcase },
  { name: "Book", code: "FaBook", icon: FaBook },
  { name: "Chart", code: "FaChartLine", icon: FaChartLine },
  { name: "Settings", code: "FaCog", icon: FaCog },
  { name: "Team", code: "FaUserFriends", icon: FaUserFriends },
  { name: "Tasks", code: "FaClipboardList", icon: FaClipboardList },
  { name: "Chat", code: "FaComments", icon: FaComments },
  { name: "Home", code: "FaHome", icon: FaHome },
  { name: "User", code: "FaUser", icon: FaUser },
  { name: "Lock", code: "FaLock", icon: FaLock },
  { name: "Unlock", code: "FaUnlock", icon: FaUnlock },
  { name: "Envelope", code: "FaEnvelope", icon: FaEnvelope },
  { name: "Phone", code: "FaPhone", icon: FaPhone },
  { name: "Calendar", code: "FaCalendar", icon: FaCalendar },
  { name: "Map Marker", code: "FaMapMarkerAlt", icon: FaMapMarkerAlt },
  { name: "Link", code: "FaLink", icon: FaLink },
  { name: "Share", code: "FaShareAlt", icon: FaShareAlt },
  { name: "Save", code: "FaSave", icon: FaSave },
  { name: "Edit", code: "FaEdit", icon: FaEdit },
  { name: "Trash", code: "FaTrash", icon: FaTrash },
  { name: "Plus", code: "FaPlus", icon: FaPlus },
  { name: "Minus", code: "FaMinus", icon: FaMinus },
  { name: "Upload", code: "FaUpload", icon: FaUpload },
  { name: "Download", code: "FaDownload", icon: FaDownload },
  { name: "File", code: "FaFile", icon: FaFile },
  { name: "File Alt", code: "FaFileAlt", icon: FaFileAlt },
  { name: "File PDF", code: "FaFilePdf", icon: FaFilePdf },
  { name: "File Word", code: "FaFileWord", icon: FaFileWord },
  { name: "File Excel", code: "FaFileExcel", icon: FaFileExcel },
  { name: "File Image", code: "FaFileImage", icon: FaFileImage },
  { name: "File Audio", code: "FaFileAudio", icon: FaFileAudio },
  { name: "File Video", code: "FaFileVideo", icon: FaFileVideo },
  { name: "File Archive", code: "FaFileArchive", icon: FaFileArchive },
  { name: "Heart", code: "FaHeart", icon: FaHeart },
  { name: "Star", code: "FaStar", icon: FaStar },
  { name: "Shopping Cart", code: "FaShoppingCart", icon: FaShoppingCart },
  { name: "Dollar Sign", code: "FaDollarSign", icon: FaDollarSign },
  { name: "Credit Card", code: "FaCreditCard", icon: FaCreditCard },
  { name: "Medkit", code: "FaMedkit", icon: FaMedkit },
  { name: "Hospital", code: "FaHospital", icon: FaHospital },
  { name: "Shower", code: "FaShower", icon: FaShower },
  { name: "Bath", code: "FaBath", icon: FaBath },
  { name: "Bed", code: "FaBed", icon: FaBed },
  { name: "Coffee", code: "FaCoffee", icon: FaCoffee },
  { name: "Beer", code: "FaBeer", icon: FaBeer },
  { name: "Pizza Slice", code: "FaPizzaSlice", icon: FaPizzaSlice },
  { name: "Apple", code: "FaApple", icon: FaApple },
  { name: "Android", code: "FaAndroid", icon: FaAndroid },
  { name: "Windows", code: "FaWindows", icon: FaWindows },
  { name: "Linux", code: "FaLinux", icon: FaLinux },
  { name: "Apple Alt", code: "FaAppleAlt", icon: FaAppleAlt },
  { name: "Basketball Ball", code: "FaBasketballBall", icon: FaBasketballBall },
  { name: "Football Ball", code: "FaFootballBall", icon: FaFootballBall },
  { name: "Baseball Ball", code: "FaBaseballBall", icon: FaBaseballBall },
  { name: "Table Tennis", code: "FaTableTennis", icon: FaTableTennis },
  { name: "Golf Ball", code: "FaGolfBall", icon: FaGolfBall },
  { name: "Tachometer Alt", code: "FaTachometerAlt", icon: FaTachometerAlt },
  { name: "Running", code: "FaRunning", icon: FaRunning },
  { name: "Dumbbell", code: "FaDumbbell", icon: FaDumbbell },
  { name: "Archway", code: "FaArchway", icon: FaArchway },
  { name: "Building", code: "FaBuilding", icon: FaBuilding },
  { name: "City", code: "FaCity", icon: FaCity },
  { name: "Store", code: "FaStore", icon: FaStore },
  { name: "Warehouse", code: "FaWarehouse", icon: FaWarehouse },
  { name: "Truck", code: "FaTruck", icon: FaTruck },
  { name: "Ship", code: "FaShip", icon: FaShip },
  { name: "Plane", code: "FaPlane", icon: FaPlane },
  { name: "Train", code: "FaTrain", icon: FaTrain },
  { name: "Taxi", code: "FaTaxi", icon: FaTaxi },
  { name: "Subway", code: "FaSubway", icon: FaSubway },
  { name: "Bicycle", code: "FaBicycle", icon: FaBicycle },
  { name: "Walking", code: "FaWalking", icon: FaWalking },
  { name: "Mountain", code: "FaMountain", icon: FaMountain },
  { name: "Sun", code: "FaSun", icon: FaSun },
  { name: "Moon", code: "FaMoon", icon: FaMoon },
  { name: "Cloud", code: "FaCloud", icon: FaCloud },
  { name: "Cloud Sun", code: "FaCloudSun", icon: FaCloudSun },
  { name: "Cloud Moon", code: "FaCloudMoon", icon: FaCloudMoon },
  { name: "Umbrella", code: "FaUmbrella", icon: FaUmbrella },
  { name: "Snowflake", code: "FaSnowflake", icon: FaSnowflake },
  { name: "Wind", code: "FaWind", icon: FaWind },
  { name: "Layer Group", code: "FaLayerGroup", icon: FaLayerGroup },
  { name: "Security", code: "FaShieldAlt", icon: FaShieldAlt },
  { name: "JS", code: "FaJs", icon: FaJs },
  { name: "CSS3", code: "FaCss3", icon: FaCss3 },
  { name: "React", code: "FaReact", icon: FaReact },
  { name: "Vue", code: "FaVuejs", icon: FaVuejs },
  { name: "Angular", code: "FaAngular", icon: FaAngular },
  { name: "Node", code: "FaNodeJs", icon: FaNodeJs },
  { name: "Python", code: "FaPython", icon: FaPython },
  { name: "Java", code: "FaJava", icon: FaJava },
  { name: "PHP", code: "FaPhp", icon: FaPhp },
  { name: "Swift", code: "FaSwift", icon: FaSwift },
  { name: "Rust", code: "FaRust", icon: FaRust },
  { name: "R", code: "FaRProject", icon: FaRProject },
  { name: "SQL", code: "FaDatabase", icon: FaDatabase },
  { name: "Jenkins", code: "FaJenkins", icon: FaJenkins },
  { name: "Flask", code: "FaFlask", icon: FaFlask },
  { name: "Laravel", code: "FaLaravel", icon: FaLaravel },
  { name: "Docker", code: "FaDocker", icon: FaDocker },
  { name: "GitLab", code: "FaGitlab ", icon: FaGitlab },
  { name: "Open Book", code: "FaBookOpen ", icon: FaBookOpen },
  { name: "Calendar Check", code: "FaCalendarCheck", icon: FaCalendarCheck },
  { name: "Terminal", code: "FaTerminal", icon: FaTerminal },
  { name: "Book Reader", code: "FaBookReader", icon: FaBookReader },
  { name: "Calendar Day", code: "FaCalendarDay", icon: FaCalendarDay },
  { name: "Github", code: "FaGithub", icon: FaGithub },
  { name: "Sync", code: "FaSync", icon: FaSync },
  { name: "Graduation Cap", code: "FaGraduationCap", icon: FaGraduationCap },
  { name: "Play Circle", code: "FaPlayCircle", icon: FaPlayCircle },
  { name: "University", code: "FaUniversity", icon: FaUniversity },
  { name: "Code Branch", code: "FaCodeBranch", icon: FaCodeBranch },
  { name: "Site Map", code: "FaSitemap ", icon: FaSitemap },
  { name: "Calculator", code: "FaCalculator", icon: FaCalculator },
  { name: "Project Diagram", code: "FaProjectDiagram", icon: FaProjectDiagram },
  { name: "Network Wired", code: "FaNetworkWired", icon: FaNetworkWired },
  { name: "History", code: "FaHistory", icon: FaHistory },
  { name: "Robot", code: "FaRobot", icon: FaRobot },
  { name: "Users", code: "FaUsers", icon: FaUsers },
  { name: "Thumbs Up", code: "FaThumbsUp", icon: FaThumbsUp },
  { name: "Arrow Up Right", code: "GoArrowUpRight", icon: GoArrowUpRight },
  { name: "Thunder", code: "GoZap", icon: GoZap },
  {
    name: "Square Rounded Chevrons Up Filled",
    code: "TbSquareRoundedChevronsUpFilled",
    icon: TbSquareRoundedChevronsUpFilled,
  },
];
